### ISSUE TITLE
Не работет пагинация в data widgets

### ISSUE THREAD

**Issue by impuulse** [howardEagle/yii2-inline-widgets-behavior#9]
Приветствую! Не работает пагинация в ListView в виджете, встроенным вашим поведением. Подскажите как решить эту проблему?

**Comment by demogorgorn** [comment]
Я не автор. Не работает ajax пагинация или обычная методом get?
Для своего проекта делал расширенную версию этого компонента, которая добавляет использования ajax виджетами.

Приведите пример вашего кода

**Comment by outOFFspace** [comment]
Спробував підключити віджет з ListView - пагінація працює
